<?php

namespace App\Controller\Admin;

class BaseController extends \App\Controller\AppController
{

    public function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->checkLogin();
    }

    protected function checkLogin() {
        $controller = $this->request->getParam('controller');
        if ($controller == "Login") {
            return;
        }
        if (empty($_SESSION["logininfo"]) || $_SESSION["logininfo"]["rule"] != "admin") {
            $this->redirect("/login");
            return;
        }
    }
}
